In [2]:
import torch

In [25]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [26]:
x.requires_grad_(True)
x.grad

In [31]:
y = 2 * torch.dot(x, x)
x.grad.zero_()  # Reset the gradient
y.backward()
x.grad, x.grad == 4 * x

(tensor([ 0.,  4.,  8., 12.]), tensor([True, True, True, True]))

In [34]:
x.grad.zero_()  # Reset the gradient
y = x.sum()
y.backward()
x.grad == torch.ones_like(x)

tensor([True, True, True, True])

## Jacobians and how differentiation of autograd work

我觉得可以理解Jacobian为一种表示方式，take $y = x \times 2$ , $\frac{\partial y}{\partial x}$它是一种把每一个y element对每一个x vector进行differentiate的过程，所以这个例子最后的shape是一个matrix。

Object `ones` not found.
