## pytorch data教学

n维数组，也称为张量（tensor）

好处：
1. GPU很好地支持加速计算，而NumPy仅支持CPU计算
2. 支持自动微分


## 有关tensor

In [18]:
import torch

In [19]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
x.numel()

12

In [21]:
X = x.reshape(2,2,3)
X

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])

In [22]:
X = x.reshape(4, 3)
X

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [23]:
X = x.reshape(2,2,3).transpose((0, 1, 2))
X

TypeError: transpose() received an invalid combination of arguments - got (tuple), but expected one of:
 * (int dim0, int dim1)
 * (name dim0, name dim1)


In [24]:
torch.zeros((2, 3, 4))
torch.ones((2, 3, 4))
torch.randn(3, 4)
# manual
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

## 操作类型

### element-wise 
（+、-、*、/和**）都是$F: \mathbb{R}^{S}, \mathbb{R}^{S} \rightarrow \mathbb{R}^{S}$

In [26]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y  # **运算符是求幂运算

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

更多的还有torch.exp(x)，逻辑运算等等

### 关于特定轴的运算

In [31]:
X = torch.arange(12, dtype=torch.float32).reshape(3,4)
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0),torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

#### broadcasting 和slicing
broadcasting 和slicing都是torch的语法糖。

广播机制，简要来说就是当实行$F: A, B \rightarrow \mathbb{R}^{S}, A \in \mathbb{R}^{S}, B \in \mathbb{R}^{S}$ element-wise操作时：当A, B的shape不匹配的时候，系统自动填充成双方match的形状，然后正常进行$F$的操作。

slicing, 来看下面的例子。

In [32]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [34]:
# 可以用: 来mark一整行的操作。
X[0:2, :]

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.]])

In [35]:
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

## 一些优化

### 内存

In [ ]:
# 良好的内存使用，python不会重新分配内存给Z
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 140160300928112
id(Z): 140160300928112


In [37]:
# 糟糕的内存使用，python会重新分配内存给Z
before = id(Y)
Y = Y + X
id(Y) == before

False

### 转换对象

In [ ]:
# 因为底部共享内存，所以pytorch和numpy转换相当方便。
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [ ]:
# pytorch和python标量转换
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)